name: App Deploy

on:
  workflow_run:
    workflows:
      - Infra Deploy
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Print test
        run: echo "YAML is valid"
name: App Deploy

on:
workflow_run:
workflows:
- Infra Deploy
types:
- completed

jobs:
deploy:
if: ${{ github.event.workflow_run.conclusion == 'success' }}
runs-on: ubuntu-latest

steps:
  - name: Print test
    run: echo "YAML is valid"